name: main_workflow
on: [push]
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/nodejs_jest_job'
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/nodejs_jest_job'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest && npm test
